// ContentListPage
export const GET_CONTENT_PLAYLIST = 'GET_CONTENT_PLAYLIST'

// Counters
export const INCREMENT_OR_DECREMENT = 'INCREMENT_OR_DECREMENT'

// Details
export const GET_DETAILS_MEDIA = 'GET_DETAILS_MEDIA'
